#pragma 

#include "ChatStruct.h"
#include "Login.h"
#include "ResponseLogin.h"
#include "Control.h"
#include "Signup.h"
#include "ResponseSignup.h"
#include "UserStatus.h"
#include "PrivateChat.h"
#include "PrivateFile.h"
#include "RequestSendFile.h"
#include "ResponseSendFile.h"
#include "ChangePassword.h"
#include "ResponseChangePassword.h"
#include "LoginNotification.h"
#include "LogoutNotification.h"
#include "SetInfor.h"
#include "RequestInfor.h"
#include "ResponseInfor.h"